spring:
  datasource:
    url: jdbc:h2:file:~/SavingsTrackerAPI
    username:
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        trace: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: h2

application:
  security:
    jwt:
      secret-key: 4D6251655468576D597133743677397A24432646294A404E635266556A586E32
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
