spring:
  datasource:
    url: jdbc:postgresql://db:5432/savings_tracker
    username: remo1921
    password: Remo1921
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 4D6251655468576D597133743677397A24432646294A404E635266556A586E32
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
